CREATE USER [SqlUser]
	For LOGIN [SqlUser]
	WITH DEFAULT_SCHEMA = dbo

GO

GRANT CONNECT TO [SqlUser];
GO
GRANT ALTER TO [SqlUser];
GO
GRANT CREATE FUNCTION TO [SqlUser];
GO
GRANT CREATE PROCEDURE TO [SqlUser];
GO
GRANT CREATE TABLE TO [SqlUser];
GO
GRANT CREATE VIEW TO [SqlUser];
GO
GRANT DELETE TO [SqlUser];
GO
GRANT EXECUTE TO [SqlUser];
GO
GRANT INSERT TO [SqlUser];
GO
GRANT SELECT TO [SqlUser];
GO
GRANT UPDATE TO [SqlUser];
GO
GRANT VIEW DEFINITION TO [SqlUser];
GO
